2022-03-10 08:29:19,716 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\lab7_210569951_WongHangKit\microblog\app\__init__.py:43]
2022-03-10 08:29:27,466 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\lab7_210569951_WongHangKit\microblog\app\__init__.py:43]
2022-03-10 08:40:42,444 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 08:42:29,256 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 08:42:40,204 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 08:44:19,740 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 08:49:07,133 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 09:11:28,653 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 09:12:19,970 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 09:14:37,602 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-10 09:16:01,788 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-17 07:47:21,968 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-17 08:09:28,542 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:43]
2022-03-17 08:34:21,739 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:45]
2022-03-17 08:35:20,748 ERROR: Exception on /reset_password_request [POST] [in C:\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Administrator\PycharmProjects\microblog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Administrator\PycharmProjects\microblog\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Administrator\PycharmProjects\microblog\app\models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2022-03-17 08:41:41,375 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:45]
2022-03-17 08:42:23,567 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:45]
2022-03-17 09:12:11,943 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:47]
2022-03-24 07:32:49,995 INFO: Microblog startup [in C:\Users\Administrator\PycharmProjects\microblog\app\__init__.py:49]
2022-03-24 07:32:55,356 ERROR: Exception on /favicon.ico [GET] [in C:\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing.py", line 2042, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Administrator\PycharmProjects\microblog\app\errors.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "C:\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Python310\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\PycharmProjects\microblog\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
2022-03-24 07:32:59,810 ERROR: Exception on /favicon.ico [GET] [in C:\Python310\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1492, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1474, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "C:\Python310\lib\site-packages\flask\ctx.py", line 376, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Python310\lib\site-packages\werkzeug\routing.py", line 2042, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1386, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1326, in handle_http_exception
    return self.ensure_sync(handler)(e)
  File "C:\Users\Administrator\PycharmProjects\microblog\app\errors.py", line 7, in not_found_error
    return render_template('404.html'), 404
  File "C:\Python310\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Python310\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Administrator\PycharmProjects\microblog\app\templates\404.html", line 1, in top-level template code
    {% extends "base.html" %}
jinja2.exceptions.TemplateRuntimeError: extended multiple times
